name: Format code

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "src/**"
      - ".github/workflows/format.yml"

jobs:
  format-code:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Run clang-format
        run: |
          sudo apt install clang-format -y
          clang-format -i -style=file:".clang-format" src/**/*.h  
          clang-format -i -style=file:".clang-format" src/**/*.c
      - name: Commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          branch: main
          commit_message: "auto: Format code"
          commit_user_name: "gh-actions[bot]"
          commit_user_email: "action@github.com"
          commit_author: "gh-actions[bot] <action@github.com>"
